### ISSUE TITLE
Version heavily outdated

### ISSUE THREAD

**Issue by Vampire** [lluccia/chocolatey-jedit#1]
4 years ago 5.6.0 was released and a few hours I released 5.7.0, but the choco package is still at 5.5.0.
Please bring out an update. :-)

**Comment by lluccia** [comment]
Hello @Vampire, thanks for the information.

I updated the package code with versions 5.6.0 and 5.7.0 (in separate branches).
I am currently using Linux environments and trying to create an environment to test the packages before publishing to Chocolatey repo.

Are you a jEdit maintainer? Are you interested in take over the Chocolatey package maintenance?

**Comment by Vampire** [comment]
> Are you a jEdit maintainer?

Yes

> Are you interested in take over the Chocolatey package maintenance?

Not right now, thanks.
I'm not having the capacity to get familiar with choco and powershell and how all parts work together,
I'm not even using choco, just have seen at a colleague's box that he is using that heavily outdated version.

But thank you, that you are creating and maintaining this.
You might want to subscribe to the [jEdit Announce mailinglist](https://sourceforge.net/p/jedit/mailman/) to get notified earlier about releases in the future and not just a couple of years later. :-D

**Comment by lluccia** [comment]
Versions  5.6.0 and 5.7.0 published to chocolatey community repo:

https://community.chocolatey.org/packages/jEdit/5.6.0
https://community.chocolatey.org/packages/jEdit/5.7.0
